# Generated by Django 3.2.2 on 2021-07-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='price_amount',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='price_currency',
        ),
        migrations.AddField(
            model_name='nft',
            name='nft_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='token_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='txhash',
            field=models.URLField(blank=True, null=True),
        ),
    ]
