# Generated by Django 3.2.2 on 2021-07-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210715_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='nfts/thumbnails'),
        ),
    ]
