# Generated by Django 3.2.2 on 2021-07-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_copy_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='search_vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
