# Generated by Django 3.2.2 on 2021-08-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210803_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='sold',
        ),
    ]
