# Generated by Django 3.2.2 on 2021-08-13 03:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_nft_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedNFT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_id', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer', models.CharField(blank=True, max_length=255, null=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.nft')),
            ],
        ),
    ]
