# Generated by Django 3.2.2 on 2021-08-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_purchasednft'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasednft',
            name='txhash',
            field=models.URLField(blank=True, null=True),
        ),
    ]
