# Generated by Django 3.2.2 on 2021-08-13 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_purchasednft_txhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasednft',
            name='nft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.nft'),
        ),
    ]
