# Generated by Django 3.2.2 on 2021-08-17 21:11

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_nft_minted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='media',
            field=models.FileField(upload_to=catalog.models.PathAndRename('nfts')),
        ),
        migrations.AlterField(
            model_name='nft',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=catalog.models.PathAndRename('thumbnails')),
        ),
    ]
