RELEASE_VERSION ?= HEAD

api_init:
	packer init api.pkr.hcl

api_format:
	packer fmt api.pkr.hcl

api_build:
	packer build api.pkr.hcl

worker_init:
	packer init worker.pkr.hcl

worker_format:
	packer fmt worker.pkr.hcl

worker_build:
	packer build worker.pkr.hcl
