# Generated by Django 3.2.2 on 2021-07-13 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot', models.CharField(choices=[('1X1', '1X1'), ('2X1', '2X1'), ('3X1', '3X1'), ('4X1', '4X1'), ('1X2', '1X2'), ('1X3', '1X3'), ('1X4', '1X4')], help_text='Columns x Rows. 2X1 means two columns width and 1 row height.', max_length=10)),
                ('image', models.ImageField(upload_to='images/ads')),
                ('clicks', models.IntegerField(default=0)),
                ('renders', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
