# Generated by Django 3.2.2 on 2021-07-13 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kyc.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('address', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KYCModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=250)),
                ('performer_name', models.CharField(max_length=250)),
                ('username', models.SlugField(max_length=110, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('PENDING', 'PENDING'), ('VERIFIED', 'VERIFIED'), ('REJECTED', 'REJECTED')], default='NEW', max_length=20)),
                ('birth_date', models.DateField(validators=[kyc.models.validate_over_18])),
                ('id_card_front', models.ImageField(upload_to='images/kyc')),
                ('id_card_back', models.ImageField(upload_to='images/kyc')),
                ('id_card_selfie', models.ImageField(upload_to='images/kyc')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/profile')),
                ('cover_picture', models.ImageField(blank=True, null=True, upload_to='images/profile/cover')),
                ('biography', models.TextField(blank=True, null=True)),
                ('tos_accepted', models.BooleanField(default=False)),
                ('consent_promotional_use', models.BooleanField(default=False)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.wallet', unique=True)),
            ],
        ),
    ]
