# Generated by Django 3.2.2 on 2021-08-17 21:12

from django.db import migrations, models
import kyc.models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to=kyc.models.PathAndRename('images/profile/cover')),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='id_card_back',
            field=models.ImageField(upload_to=kyc.models.PathAndRename('images/kyc/id_card_back')),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='id_card_front',
            field=models.ImageField(upload_to=kyc.models.PathAndRename('images/kyc/id_card_front')),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='id_card_selfie',
            field=models.ImageField(upload_to=kyc.models.PathAndRename('images/kyc/id_card_selfie')),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=kyc.models.PathAndRename('images/profile')),
        ),
    ]
