abi = [{"inputs": [{"internalType": "address", "name": "_modelContractBase", "type": "address"},
                   {"internalType": "address", "name": "_mainToken", "type": "address"}],
        "stateMutability": "nonpayable", "type": "constructor"}, {"anonymous": False, "inputs": [
    {"indexed": True, "internalType": "address", "name": "contractAddress", "type": "address"},
    {"indexed": False, "internalType": "uint256", "name": "nftId", "type": "uint256"},
    {"indexed": False, "internalType": "string", "name": "uri", "type": "string"},
    {"indexed": False, "internalType": "uint256", "name": "mintCap", "type": "uint256"},
    {"indexed": False, "internalType": "address", "name": "token", "type": "address"},
    {"indexed": False, "internalType": "uint256", "name": "tokenAmount", "type": "uint256"}], "name": "AddNft",
                                                                  "type": "event"}, {"anonymous": False, "inputs": [
    {"indexed": True, "internalType": "address", "name": "contractAddress", "type": "address"},
    {"indexed": True, "internalType": "address", "name": "walletAddress", "type": "address"},
    {"indexed": False, "internalType": "string", "name": "modelName", "type": "string"}],
                                                                                     "name": "NewCollectionContract",
                                                                                     "type": "event"},
       {"anonymous": False,
        "inputs": [{"indexed": True, "internalType": "address", "name": "contractAddress", "type": "address"},
                   {"indexed": False, "internalType": "address", "name": "buyer", "type": "address"},
                   {"indexed": False, "internalType": "uint256", "name": "nftId", "type": "uint256"},
                   {"indexed": False, "internalType": "uint256", "name": "tokenId", "type": "uint256"},
                   {"indexed": False, "internalType": "uint256", "name": "mintCap", "type": "uint256"},
                   {"indexed": False, "internalType": "uint256", "name": "minted", "type": "uint256"},
                   {"indexed": False, "internalType": "string", "name": "modelName", "type": "string"}],
        "name": "PurchaseNft", "type": "event"}, {"anonymous": False, "inputs": [
        {"indexed": True, "internalType": "address", "name": "contractAddress", "type": "address"},
        {"indexed": True, "internalType": "address", "name": "from", "type": "address"},
        {"indexed": True, "internalType": "address", "name": "to", "type": "address"},
        {"indexed": False, "internalType": "uint256", "name": "amount", "type": "uint256"},
        {"indexed": False, "internalType": "address", "name": "token", "type": "address"}], "name": "ReferralPay",
                                                  "type": "event"}, {"anonymous": False, "inputs": [
        {"indexed": True, "internalType": "address", "name": "contractAddress", "type": "address"},
        {"indexed": True, "internalType": "address", "name": "from", "type": "address"},
        {"indexed": True, "internalType": "address", "name": "to", "type": "address"},
        {"indexed": False, "internalType": "uint256", "name": "nftId", "type": "uint256"},
        {"indexed": False, "internalType": "uint256", "name": "tokenId", "type": "uint256"}], "name": "TransferNft",
                                                                     "type": "event"},
       {"inputs": [{"internalType": "address", "name": "newAdminAddress", "type": "address"}], "name": "addAdmin",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "nonpayable",
        "type": "function"},
       {"inputs": [{"internalType": "address", "name": "tokenAddress", "type": "address"}], "name": "addPaymentToken",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "nonpayable",
        "type": "function"}, {"inputs": [{"internalType": "address", "name": "", "type": "address"}], "name": "admins",
                              "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
                              "stateMutability": "view", "type": "function"},
       {"inputs": [{"internalType": "address", "name": "modelAddress", "type": "address"}], "name": "blacklist",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "nonpayable",
        "type": "function"},
       {"inputs": [], "name": "getFarmAddress", "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view", "type": "function"},
       {"inputs": [], "name": "getFeeSplitter", "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view", "type": "function"},
       {"inputs": [], "name": "getMainToken", "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view", "type": "function"},
       {"inputs": [{"internalType": "address", "name": "modelAddress", "type": "address"}], "name": "getModelContract",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}], "stateMutability": "view",
        "type": "function"}, {"inputs": [], "name": "getPaymentTokens",
                              "outputs": [{"internalType": "address[]", "name": "", "type": "address[]"}],
                              "stateMutability": "view", "type": "function"},
       {"inputs": [], "name": "getPlatformFee", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view", "type": "function"}, {"inputs": [], "name": "getPlatformOwner", "outputs": [
        {"internalType": "address", "name": "", "type": "address"}], "stateMutability": "view", "type": "function"}, {
           "inputs": [{"internalType": "uint256", "name": "nftId", "type": "uint256"},
                      {"internalType": "string", "name": "uri", "type": "string"},
                      {"internalType": "uint256", "name": "mintCap", "type": "uint256"},
                      {"internalType": "address", "name": "token", "type": "address"},
                      {"internalType": "uint256", "name": "tokenAmount", "type": "uint256"}], "name": "logAddNft",
           "outputs": [], "stateMutability": "nonpayable", "type": "function"}, {
           "inputs": [{"internalType": "address", "name": "buyer", "type": "address"},
                      {"internalType": "uint256", "name": "nftId", "type": "uint256"},
                      {"internalType": "uint256", "name": "tokenId", "type": "uint256"},
                      {"internalType": "uint256", "name": "mintCap", "type": "uint256"},
                      {"internalType": "uint256", "name": "minted", "type": "uint256"},
                      {"internalType": "string", "name": "modelName", "type": "string"}], "name": "logPurchaseNft",
           "outputs": [], "stateMutability": "nonpayable", "type": "function"}, {
           "inputs": [{"internalType": "address", "name": "from", "type": "address"},
                      {"internalType": "address", "name": "to", "type": "address"},
                      {"internalType": "uint256", "name": "amount", "type": "uint256"},
                      {"internalType": "address", "name": "token", "type": "address"}], "name": "logReferralPay",
           "outputs": [], "stateMutability": "nonpayable", "type": "function"}, {
           "inputs": [{"internalType": "address", "name": "from", "type": "address"},
                      {"internalType": "address", "name": "to", "type": "address"},
                      {"internalType": "uint256", "name": "nftId", "type": "uint256"},
                      {"internalType": "uint256", "name": "tokenId", "type": "uint256"}], "name": "logTransferNft",
           "outputs": [], "stateMutability": "nonpayable", "type": "function"},
       {"inputs": [{"internalType": "address", "name": "modelAddress", "type": "address"}],
        "name": "modelIsBlacklisted", "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view", "type": "function"},
       {"inputs": [{"internalType": "address", "name": "", "type": "address"}], "name": "models",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}], "stateMutability": "view",
        "type": "function"}, {"inputs": [{"internalType": "string", "name": "modelName", "type": "string"},
                                         {"internalType": "string", "name": "modelDesc", "type": "string"},
                                         {"internalType": "string", "name": "modelGender", "type": "string"},
                                         {"internalType": "address", "name": "referrer", "type": "address"},
                                         {"internalType": "string", "name": "_salt", "type": "string"}],
                              "name": "newCollectionContract", "outputs": [
            {"internalType": "address", "name": "modelContractAddress", "type": "address"}],
                              "stateMutability": "nonpayable", "type": "function"},
       {"inputs": [{"internalType": "uint256", "name": "", "type": "uint256"}], "name": "paymentTokens",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}], "stateMutability": "view",
        "type": "function"},
       {"inputs": [], "name": "platformFee", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view", "type": "function"}, {"inputs": [], "name": "referralDuration", "outputs": [
        {"internalType": "uint256", "name": "", "type": "uint256"}], "stateMutability": "view", "type": "function"},
       {"inputs": [], "name": "referrerFee", "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view", "type": "function"},
       {"inputs": [{"internalType": "address", "name": "newAdminAddress", "type": "address"}], "name": "removeAdmin",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "nonpayable",
        "type": "function"}, {"inputs": [{"internalType": "address", "name": "tokenAddress", "type": "address"}],
                              "name": "removePaymentToken",
                              "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
                              "stateMutability": "nonpayable", "type": "function"},
       {"inputs": [{"internalType": "address", "name": "_farmAddress", "type": "address"}], "name": "setFarmAddress",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "nonpayable",
        "type": "function"},
       {"inputs": [{"internalType": "address", "name": "_feeSplitter", "type": "address"}], "name": "setFeeSplitter",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "nonpayable",
        "type": "function"},
       {"inputs": [{"internalType": "address", "name": "_mainToken", "type": "address"}], "name": "setMainToken",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "nonpayable",
        "type": "function"},
       {"inputs": [{"internalType": "uint256", "name": "_platformFee", "type": "uint256"}], "name": "setPlatformFee",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "nonpayable",
        "type": "function"}, {"inputs": [{"internalType": "uint256", "name": "_referralDuration", "type": "uint256"}],
                              "name": "setReferralDuration",
                              "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
                              "stateMutability": "nonpayable", "type": "function"},
       {"inputs": [{"internalType": "uint256", "name": "_referrerFee", "type": "uint256"}], "name": "setReferrerFee",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "nonpayable",
        "type": "function"},
       {"inputs": [{"internalType": "address", "name": "_masterOwner", "type": "address"}], "name": "transferOwnership",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "nonpayable",
        "type": "function"},
       {"inputs": [{"internalType": "address", "name": "modelAddress", "type": "address"}], "name": "unBlacklist",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "nonpayable",
        "type": "function"},
       {"inputs": [{"internalType": "address", "name": "", "type": "address"}], "name": "verifiedModels",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "view",
        "type": "function"},
       {"inputs": [{"internalType": "address", "name": "modelAddress", "type": "address"}], "name": "verifyModel",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "nonpayable",
        "type": "function"}]
